import javax.swing.*;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrameAdmin2.java
 *
 * Created on Oct 6, 2018, 8:01:13 PM
 */

/**
 *
 * @author Ramanatha Tawker
 */
public class NewJFrameAdmin2 extends javax.swing.JFrame {

    /** Creates new form NewJFrameAdmin2 */
    public NewJFrameAdmin2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SCREEN1", "SCREEN2", "SCREEN3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("RESET YOUR MOVIE");

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con1;
            con1=DriverManager.getConnection("jdbc:mysql://localhost/mydb","root","");
            Statement st=con1.createStatement();
            if(jComboBox1.getSelectedItem().toString().equals("SCREEN1")){
            String query="update chennai set SEAT1=1 , SEAT2=1 , SEAT3=1 , SEAT4=1 , SEAT5=1 , SEAT6=1 , SEAT7=1 , SEAT8=1 , SEAT9=1 , SEAT10=1 , SEAT11=1 , SEAT12=1 , SEAT13=1 , SEAT14=1 , SEAT15=1 , SEAT16=1 , SEAT17=1 , SEAT18=1 , SEAT19=1 , SEAT20=1 , SEAT21=1 , SEAT22=1 , SEAT23=1 , SEAT24=1 , SEAT25=1 , SEAT26=1 , SEAT27=1 , SEAT28=1 , SEAT29=1 ,SEAT30=1,date=ADDDATE(date(sysdate()),1) where MOVIENAME='MOVIE961200';";
            int c=st.executeUpdate(query);
            if(c>0){
                JOptionPane.showMessageDialog(null,"SCREEN-1 Seats have been reseted and date has been changed for next set of bookings");
            }}
            if(jComboBox1.getSelectedItem().toString().equals("SCREEN2")){
            String query="update chennai set SEAT1=1 , SEAT2=1 , SEAT3=1 , SEAT4=1 , SEAT5=1 , SEAT6=1 , SEAT7=1 , SEAT8=1 , SEAT9=1 , SEAT10=1 , SEAT11=1 , SEAT12=1 , SEAT13=1 , SEAT14=1 , SEAT15=1 , SEAT16=1 , SEAT17=1 , SEAT18=1 , SEAT19=1 , SEAT20=1 , SEAT21=1 , SEAT22=1 , SEAT23=1 , SEAT24=1 , SEAT25=1 , SEAT26=1 , SEAT27=1 , SEAT28=1 , SEAT29=1 ,SEAT30=1,date=ADDDATE(date(sysdate()),1) where MOVIENAME='MOVIESANDA1200';";
            int c=st.executeUpdate(query);
            if(c>0){
                JOptionPane.showMessageDialog(null,"SCREEN-2 Seats have been reseted and date has been changed for next set of bookings");
            }}
            if(jComboBox1.getSelectedItem().toString().equals("SCREEN3")){
            String query="update chennai set SEAT1=1 , SEAT2=1 , SEAT3=1 , SEAT4=1 , SEAT5=1 , SEAT6=1 , SEAT7=1 , SEAT8=1 , SEAT9=1 , SEAT10=1 , SEAT11=1 , SEAT12=1 , SEAT13=1 , SEAT14=1 , SEAT15=1 , SEAT16=1 , SEAT17=1 , SEAT18=1 , SEAT19=1 , SEAT20=1 , SEAT21=1 , SEAT22=1 , SEAT23=1 , SEAT24=1 , SEAT25=1 , SEAT26=1 , SEAT27=1 , SEAT28=1 , SEAT29=1 ,SEAT30=1,date=ADDDATE(date(sysdate()),1) where MOVIENAME='MOVIENT1200';";
            int c=st.executeUpdate(query);
            if(c>0){
                JOptionPane.showMessageDialog(null,"SCREEN-3 Seats have been reseted and date has been changed for next set of bookings");
            }}
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameAdmin2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
